"""Hourly heartbeat leaves: registration, create-ahead, expiry sweep.

The heartbeat class registers into the shared retention-class table with
a horizon DERIVED from the configured staleness thresholds — heartbeats
matter only while they can refute a staleness verdict, so retention is
`max(stale_after, finalizing_stale_after) x safety_factor` with a
one-hour floor, recomputed from configuration at every registration and
never a constant. Because the horizon is operational drop cadence rather
than a promise snapshotted onto requests, a changed configuration
UPDATES the stored duration (a typed outcome) instead of conflicting —
the immutability rule that protects history classes protects enqueue
snapshots, and nothing snapshots the heartbeat class.

Leaves are hourly, cataloged in the shared leaf catalog under the
reserved class key, and detached/dropped by the same manager machinery
history leaves use — `detach_expired_leaf` and `drop_detached_leaf` are
interval-agnostic, and a heartbeat leaf can never be pending-blocked
because no pending locator carries the reserved class. Creation is
heartbeat-specific: the per-leaf index is the stale probe's
`(task_id, role, sent_at DESC)` shape, not the history task-ID index,
and no loader republish accompanies it because the manifest excludes the
reserved class at assembly. Bounded relations per transaction: one leaf.

Registration requires the partitioned parent to exist: parent creation
belongs to the install and migration programs, and a deployment still on
the unpartitioned table is a typed refusal, not hidden DDL.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncConnection

from ..maintenance.database import PartitionMaintenanceDatabase
from ..commands import (
    DETACH_STATEMENT_TIMEOUT_MS,
    DetachExpiredHistoryLeaf,
    DropDetachedHistoryLeaf,
    InspectHistoryLeaf,
    LeafBounds,
    LeafRef,
    is_safe_identifier,
)
from ..errors import HistoryContractError
from ..names import (
    HEARTBEAT_CLASS_KEY,
    HEARTBEATS_TABLE,
    LEAF_CATALOG,
    RETENTION_CLASSES,
)
from ..outcomes import (
    CatalogConflictKind,
    LeafAlreadyConformant,
    LeafCatalogConflict,
    LeafCreated,
    LeafCreation,
    LeafDetached,
    LeafDrop,
    LeafIndexRepaired,
    LeafInspection,
    LeafMaintenanceBusy,
    RetentionClassAbsent,
)
from ..partitions.catalog import (
    INDEX_SCHEMA_VERSION,
    LeafCatalogRow,
    LeafPhysicalState,
    RetentionClassRow,
    capture_partition_bound_utc,
    database_now,
    read_leaf_catalog_row,
    read_leaf_physical_state,
    read_retention_class,
)
from ..partitions.locks import (
    LeafLockAttempt,
    try_lock_leaf_for_transaction,
    try_lock_relation_exclusive_for_transaction,
)
from ..partitions.manager import detach_expired_leaf, drop_detached_leaf, inspect_leaf
from ..partitions.publication import LoaderPublication
from ..phase2.quarantine import QuarantineRefused

_HOURLY = timedelta(hours=1)
_HORIZON_FLOOR = timedelta(hours=1)

HEARTBEATS_PARTITIONED_DDL = f"""
CREATE TABLE {HEARTBEATS_TABLE} (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    task_id uuid NOT NULL,
    sender_id varchar(255) NOT NULL,
    role varchar(20) NOT NULL,
    sent_at timestamptz NOT NULL,
    hostname varchar(255),
    pid integer
) PARTITION BY RANGE (sent_at)
"""
"""The cutover shape: RANGE on `sent_at` directly (no LIST parent —
heartbeats have no retention classes and never enter history), created
EMPTY at migration because heartbeats are transient. `task_id` is uuid,
not the current varchar(36): post-cutover task identity is uuid, the
stale probe compares against the live `id` column directly, and an
empty-at-cutover table owes the old encoding nothing. No primary key: a
partitioned key would have to include `sent_at`, and no reader addresses
heartbeats by identity. The retention-serving `sent_at` index does not
carry over; retention is leaf drop."""


def hourly_leaf_name(lower: datetime) -> str:
    """The leaf relation name for the hour starting at `lower`."""
    name = f'{HEARTBEATS_TABLE}_{lower:%Y_%m_%d_%H}'
    if not is_safe_identifier(name):
        raise ValueError(f'{name!r} is not a safe identifier')
    return name


def probe_index_name(leaf_name: str) -> str:
    """The per-leaf stale-probe index name."""
    name = f'{leaf_name}_probe_idx'
    if not is_safe_identifier(name):
        raise ValueError(f'{name!r} is not a safe identifier')
    return name


def heartbeat_horizon(
    *,
    stale_after: timedelta,
    finalizing_stale_after: timedelta,
    safety_factor: int,
) -> timedelta:
    """Derive the heartbeat retention horizon from staleness thresholds.

    `max(stale_after, finalizing_stale_after) x safety_factor`, floored
    at one hour. All three inputs come from configuration; none is a
    constant here.
    """
    if stale_after <= timedelta(0) or finalizing_stale_after <= timedelta(0):
        raise ValueError('staleness thresholds must be positive')
    if safety_factor < 1:
        raise ValueError('safety factor must be at least 1')
    derived = max(stale_after, finalizing_stale_after) * safety_factor
    return max(derived, _HORIZON_FLOOR)


# ---------------------------------------------------------------------------
# Class registration
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class HeartbeatClassRegistered:
    """The heartbeat class row now exists with the derived horizon."""

    horizon: timedelta


@dataclass(frozen=True, slots=True)
class HeartbeatClassVerified:
    """An identical registration already exists; nothing changed."""

    horizon: timedelta


@dataclass(frozen=True, slots=True)
class HeartbeatHorizonUpdated:
    """Configuration changed the derived horizon; the stored duration
    was updated. Drop cadence shifts; nothing else does."""

    previous_horizon: timedelta
    horizon: timedelta


@dataclass(frozen=True, slots=True)
class HeartbeatParentUnpartitioned:
    """The heartbeat table exists but is not partitioned — the deployment
    has not run the cutover migration. Registration refuses."""


type HeartbeatClassRegistration = (
    HeartbeatClassRegistered
    | HeartbeatClassVerified
    | HeartbeatHorizonUpdated
    | HeartbeatParentUnpartitioned
)


async def register_heartbeat_class(
    connection: AsyncConnection,
    *,
    horizon: timedelta,
) -> HeartbeatClassRegistration:
    """Create, verify, or update the heartbeat class registration.

    Requires the partitioned parent to already exist; a deployment still
    on the unpartitioned table receives a typed refusal.
    """
    if horizon < _HORIZON_FLOOR:
        raise ValueError('heartbeat horizon is floored at one hour')

    partitioned = (
        await connection.execute(
            text(
                """
                SELECT EXISTS (
                    SELECT 1 FROM pg_partitioned_table
                    WHERE partrelid = to_regclass(:parent)
                )
                """
            ),
            {'parent': HEARTBEATS_TABLE},
        )
    ).scalar_one()
    if not partitioned:
        return HeartbeatParentUnpartitioned()

    existing = await read_retention_class(connection, HEARTBEAT_CLASS_KEY)
    match existing:
        case None:
            await connection.execute(
                text(
                    f"""
                    INSERT INTO {RETENTION_CLASSES} (
                        class_key, duration, partition_interval,
                        finite_parent_name, created_at
                    ) VALUES (
                        :class_key, :duration, :interval,
                        :parent, statement_timestamp()
                    )
                    """
                ),
                {
                    'class_key': HEARTBEAT_CLASS_KEY,
                    'duration': horizon,
                    'interval': _HOURLY,
                    'parent': HEARTBEATS_TABLE,
                },
            )
            return HeartbeatClassRegistered(horizon=horizon)
        case RetentionClassRow(
            duration=timedelta() as stored,
            partition_interval=interval,
            finite_parent_name=parent,
        ) if interval == _HOURLY and parent == HEARTBEATS_TABLE:
            if stored == horizon:
                return HeartbeatClassVerified(horizon=horizon)
            await connection.execute(
                text(
                    f"""
                    UPDATE {RETENTION_CLASSES}
                    SET duration = :duration
                    WHERE class_key = :class_key
                    """
                ),
                {'duration': horizon, 'class_key': HEARTBEAT_CLASS_KEY},
            )
            return HeartbeatHorizonUpdated(previous_horizon=stored, horizon=horizon)
        case RetentionClassRow():
            raise HistoryContractError(
                'heartbeat class row carries a non-heartbeat shape'
            )


# ---------------------------------------------------------------------------
# Create-ahead
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class CreateHourlyHeartbeatLeaf:
    """Create or verify one hourly heartbeat leaf."""

    leaf: LeafRef

    def __post_init__(self) -> None:
        if self.leaf.bounds.upper - self.leaf.bounds.lower != _HOURLY:
            raise ValueError('heartbeat leaf bounds must span exactly one hour')
        if self.leaf.class_key != HEARTBEAT_CLASS_KEY:
            raise ValueError('heartbeat leaves carry the reserved class key')


@dataclass(frozen=True, slots=True)
class EnsureHeartbeatCoverage:
    """Create every missing hourly leaf from this hour through the horizon.

    `horizon_hours` counts complete future hourly intervals that must
    exist after this command succeeds, the current hour excluded.
    """

    horizon_hours: int

    def __post_init__(self) -> None:
        if self.horizon_hours < 2:
            raise ValueError(
                'coverage horizon below two future leaves is already the '
                'health-contract red line and cannot be a target'
            )


@dataclass(frozen=True, slots=True)
class _HourlyLeafCreationState:
    catalog: LeafCatalogRow | None
    physical: LeafPhysicalState
    outcome: LeafCreation | None


async def create_hourly_heartbeat_leaf(
    connection: AsyncConnection,
    command: CreateHourlyHeartbeatLeaf,
) -> LeafCreation:
    """Create or verify one hourly leaf inside the caller's transaction.

    No loader republish: the staged-lookup manifest excludes the reserved
    class at assembly, so no published function can reference the leaf.
    The per-leaf index is the stale probe's shape.
    """
    leaf = command.leaf
    retention_class = await read_retention_class(connection, leaf.class_key)
    if retention_class is None:
        return RetentionClassAbsent(class_key=leaf.class_key)

    state = await _read_hourly_leaf_creation_state(connection, leaf)
    if state.outcome is not None:
        return state.outcome

    lock_attempt = await try_lock_leaf_for_transaction(
        connection, class_key=leaf.class_key, anchor=leaf.bounds.lower
    )
    if lock_attempt is LeafLockAttempt.BUSY:
        return LeafMaintenanceBusy(leaf_name=leaf.leaf_name)

    state = await _read_hourly_leaf_creation_state(connection, leaf)
    if state.outcome is not None:
        return state.outcome
    catalog = state.catalog
    relation_name = leaf.leaf_name if catalog is not None else HEARTBEATS_TABLE
    relation_lock = await try_lock_relation_exclusive_for_transaction(
        connection, relation_name
    )
    if relation_lock is LeafLockAttempt.BUSY:
        return LeafMaintenanceBusy(leaf_name=leaf.leaf_name)

    index_name = probe_index_name(leaf.leaf_name)
    if catalog is not None:
        if not state.physical.id_index_exists:
            await connection.execute(
                text(
                    f'CREATE INDEX {catalog.id_index_name} '
                    f'ON {leaf.leaf_name} (task_id, role, sent_at DESC)'
                )
            )
            return LeafIndexRepaired(
                leaf_name=leaf.leaf_name,
                id_index_name=catalog.id_index_name,
            )
        raise AssertionError('a conformant heartbeat leaf returned no outcome')

    await connection.execute(
        text(
            f"""
            CREATE TABLE {leaf.leaf_name}
                PARTITION OF {HEARTBEATS_TABLE}
                FOR VALUES FROM ('{leaf.bounds.lower.isoformat()}')
                    TO ('{leaf.bounds.upper.isoformat()}')
            """
        )
    )
    # Captured under the UTC rendering convention; every later
    # comparison captures the live bound the same way.
    recorded_bound = await capture_partition_bound_utc(connection, leaf.leaf_name)
    await connection.execute(
        text(
            f"""
            INSERT INTO {LEAF_CATALOG} (
                leaf_name, parent_name, class_key,
                lower_anchor, upper_anchor,
                index_schema_version, id_index_name, partition_bound,
                min_birth_at, min_birth_verified, created_at
            ) VALUES (
                :leaf_name, :parent_name, :class_key,
                :lower, :upper,
                :index_schema_version, :id_index_name, :partition_bound,
                NULL, TRUE, statement_timestamp()
            )
            """
        ),
        {
            'leaf_name': leaf.leaf_name,
            'parent_name': HEARTBEATS_TABLE,
            'class_key': leaf.class_key,
            'lower': leaf.bounds.lower,
            'upper': leaf.bounds.upper,
            'index_schema_version': INDEX_SCHEMA_VERSION,
            'id_index_name': index_name,
            'partition_bound': recorded_bound,
        },
    )
    await connection.execute(
        text(
            f'CREATE INDEX {index_name} '
            f'ON {leaf.leaf_name} (task_id, role, sent_at DESC)'
        )
    )
    return LeafCreated(leaf_name=leaf.leaf_name, id_index_name=index_name)


async def _read_hourly_leaf_creation_state(
    connection: AsyncConnection,
    leaf: LeafRef,
) -> _HourlyLeafCreationState:
    index_name = probe_index_name(leaf.leaf_name)
    catalog = await read_leaf_catalog_row(connection, leaf.leaf_name)
    physical = await read_leaf_physical_state(
        connection,
        leaf_name=leaf.leaf_name,
        parent_name=HEARTBEATS_TABLE,
        id_index_name=(catalog.id_index_name if catalog is not None else index_name),
    )
    if physical.relation_exists != (catalog is not None):
        return _HourlyLeafCreationState(
            catalog,
            physical,
            LeafCatalogConflict(
                leaf_name=leaf.leaf_name,
                kind=CatalogConflictKind.RELATION_WITHOUT_CATALOG,
                detail=(
                    'relation exists without a catalog row'
                    if physical.relation_exists
                    else 'catalog row exists without a relation'
                ),
            ),
        )
    if catalog is None:
        return _HourlyLeafCreationState(None, physical, None)
    if (
        catalog.parent_name != HEARTBEATS_TABLE
        or catalog.class_key != leaf.class_key
        or catalog.lower_anchor != leaf.bounds.lower
        or catalog.upper_anchor != leaf.bounds.upper
        or catalog.dropped_at is not None
    ):
        outcome: LeafCreation | None = LeafCatalogConflict(
            leaf_name=leaf.leaf_name,
            kind=CatalogConflictKind.METADATA_MISMATCH,
            detail='existing leaf metadata differs from the request',
        )
        return _HourlyLeafCreationState(catalog, physical, outcome)
    if physical.partition_bound != catalog.partition_bound:
        outcome = LeafCatalogConflict(
            leaf_name=leaf.leaf_name,
            kind=CatalogConflictKind.PHYSICAL_NONCONFORMANT,
            detail='attached leaf partition bound differs from catalog',
        )
        return _HourlyLeafCreationState(catalog, physical, outcome)
    outcome = (
        LeafAlreadyConformant(leaf_name=leaf.leaf_name)
        if physical.id_index_exists
        else None
    )
    return _HourlyLeafCreationState(catalog, physical, outcome)


def hourly_leaf_ref(lower: datetime) -> LeafRef:
    """The LeafRef for the hourly leaf starting at `lower`."""
    return LeafRef(
        leaf_name=hourly_leaf_name(lower),
        class_key=HEARTBEAT_CLASS_KEY,
        bounds=LeafBounds(lower=lower, upper=lower + _HOURLY),
    )


async def ensure_heartbeat_coverage(
    connection: AsyncConnection,
    command: EnsureHeartbeatCoverage,
) -> tuple[LeafCreation, ...]:
    """Create every missing hourly leaf from this hour through the horizon.

    One outcome per required interval, oldest first; a refusal stops the
    pass, because coverage with a hole in the middle is not coverage.
    """
    now = await database_now(connection)
    hour_lower = now.replace(minute=0, second=0, microsecond=0)
    outcomes: list[LeafCreation] = []
    for hour_offset in range(command.horizon_hours + 1):
        lower = hour_lower + hour_offset * _HOURLY
        outcome = await create_hourly_heartbeat_leaf(
            connection,
            CreateHourlyHeartbeatLeaf(leaf=hourly_leaf_ref(lower)),
        )
        outcomes.append(outcome)
        match outcome:
            case LeafCreated() | LeafAlreadyConformant() | LeafIndexRepaired():
                continue
            case _:
                break
    return tuple(outcomes)


# ---------------------------------------------------------------------------
# Expiry sweep
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class HeartbeatLeafSwept:
    """One expired leaf's sweep result: the detach-side outcome and, when
    the leaf reached the detached state, the drop outcome."""

    leaf_name: str
    detach: LeafInspection | LeafMaintenanceBusy | QuarantineRefused
    drop: LeafDrop | None


async def sweep_expired_heartbeat_leaves(
    database: PartitionMaintenanceDatabase,
    publisher: LoaderPublication,
) -> tuple[HeartbeatLeafSwept, ...]:
    """Detach and drop every heartbeat leaf past its horizon.

    Discovery reads the catalog for reserved-class leaves whose upper
    bound plus the stored horizon has elapsed. Each leaf goes through the
    shared manager machinery — the same detach and drop history leaves
    use; a heartbeat leaf can never be pending-blocked because no pending
    locator carries the reserved class, so the horizon posture is None.
    One leaf per transaction (the inherited bounded-relations invariant).
    """
    async with database.connect() as connection:
        rows = (
            await connection.execute(
                text(
                    f"""
                    SELECT c.leaf_name, c.lower_anchor, c.upper_anchor
                    FROM {LEAF_CATALOG} AS c
                    JOIN {RETENTION_CLASSES} AS r
                      ON r.class_key = c.class_key
                    WHERE c.class_key = :class_key
                      AND c.dropped_at IS NULL
                      AND c.upper_anchor + r.duration
                          <= statement_timestamp()
                    ORDER BY c.lower_anchor
                    """
                ),
                {'class_key': HEARTBEAT_CLASS_KEY},
            )
        ).all()

    swept: list[HeartbeatLeafSwept] = []
    for row in rows:
        ref = LeafRef(
            leaf_name=row.leaf_name,
            class_key=HEARTBEAT_CLASS_KEY,
            bounds=LeafBounds(lower=row.lower_anchor, upper=row.upper_anchor),
        )
        detach_outcome = await detach_expired_leaf(
            database,
            DetachExpiredHistoryLeaf(
                leaf=ref,
                quarantine_horizon=None,
                statement_timeout_ms=DETACH_STATEMENT_TIMEOUT_MS,
            ),
            publisher,
        )
        drop_outcome: LeafDrop | None = None
        detached = isinstance(detach_outcome, LeafDetached)
        if not detached:
            # A crash between detach and drop leaves a detached leaf the
            # next sweep must still drop; re-inspect for that state.
            async with database.connect() as connection:
                inspection = await inspect_leaf(
                    connection, InspectHistoryLeaf(leaf=ref)
                )
            detached = isinstance(inspection, LeafDetached)
        if detached:
            async with database.begin() as connection:
                drop_outcome = await drop_detached_leaf(
                    connection,
                    DropDetachedHistoryLeaf(leaf=ref),
                    publisher,
                )
        swept.append(
            HeartbeatLeafSwept(
                leaf_name=ref.leaf_name,
                detach=detach_outcome,
                drop=drop_outcome,
            )
        )
    return tuple(swept)
